version: '3.8'

services:
  # Frontend Service
  frontend:
    build:
      context: ./services/othor-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./services/othor-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=${FRONTEND_URL}
    depends_on:
      - organizations
      - metrics
      - auth
      - narrative
      - chatbot

  # Organization Service
  organizations:
    env_file:
     - .env  
    build:
      context: ./services/backend-organizations
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8000"
    volumes:
      - ./services/backend-organizations:/app
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${SECRET_KEY}
    depends_on:
      - postgres

  # Metrics Service
  metrics:
    env_file:
     - .env
    build:
      context: ./services/backend-metrics
      dockerfile: Dockerfile.dev
    ports:
      - "8002:8000"
    volumes:
      - ./services/backend-metrics:/app
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${SECRET_KEY}
    depends_on:
      - postgres

  # Metric Discovery Service
  metric-discovery:
    env_file:
     - .env  
    build:
      context: ./services/backend-metric-discovery
      dockerfile: Dockerfile.dev
    ports:
      - "8003:8000"
    volumes:
      - ./services/backend-metric-discovery:/app
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - postgres

  # Auth Service
  auth:
    env_file:
     - .env  
    build:
      context: ./services/backend-auth
      dockerfile: Dockerfile.dev
    ports:
      - "8004:8000"
    volumes:
      - ./services/backend-auth:/app
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${SECRET_KEY}
      - JWT_ALGORITHM=${ALcGORITHM}
      - SENDER_NAME=${APP_NAME}
      - FRONTEND_URL=${FRONTEND_URL}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SENDER_EMAIL=${SENDER_EMAIL}
    depends_on:
      - postgres

  # Narrative Service
  narrative:
    env_file:
     - .env
    build:
      context: ./services/backend-narrative-and-datasource
      dockerfile: Dockerfile.dev
    ports:
      - "8005:8000"
    volumes:
      - ./services/backend-narrative-and-datasource:/app
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - postgres

  # Chatbot Service
  chatbot:
    env_file:
     - .env  
    build:
      context: ./services/backend-chatbot
      dockerfile: Dockerfile.dev
    ports:
      - "8006:8000"
    volumes:
      - ./services/backend-chatbot:/app
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - postgres

  # Database Service
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${SECRET_KEY}
      - POSTGRES_MULTIPLE_DATABASES=othor_organizations,othor_metrics,othor_auth,othor_narrative,othor_chatbot

  # Redis for caching
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    depends_on:
      - frontend
      - organizations
      - metrics
      - auth
      - narrative
      - chatbot

volumes:
  postgres_data:
  redis_data: